server:
  port: 8084

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/inventory_db
    username: root
    password: Sri#6610

  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: update
