server:
  port: 8083

spring:
  datasource:
    url: jdbc:mysql://localhost:3306/order_db
    username: root
    password: Sri#6610

  kafka:
    bootstrap-servers: localhost:9092

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
